apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  gcp:
    bigQueryDatasets:
      - name: flex_dataset
        permission: READWRITE
  accessPolicy:
    inbound:
      rules:
        - application: spinnsyn-frontend
        - application: sykepengesoknad
