server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default,createtable

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: health,prometheus

logging.config: "classpath:logback.xml"
